[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"] # Tells foundry to redirect/remap anywhere we have '@chainlink/contracts' to our local folder where we downloaded that code

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
